name: CI on PR 

on: [pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: '8.0.192'
        java-package: jdk
        architecture: x64
    - name: Run tests
      run: mvn clean test --file pom.xml
